version: "2"
run:
  go: "1.24"
linters:
  enable:
    - containedctx
    - dogsled
    - dupl
    - errorlint
    - funlen
    - nilnil
    - noctx
  settings:
    funlen:
      lines: 120
      statements: 120
    gocognit:
      min-complexity: 20
    gocyclo:
      min-complexity: 10
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - containedctx
          - funlen
          - gocognit
          - gocyclo
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
